ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'SMTP_EMAIL';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'GOOGLE_SHEETS';

ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'GOOGLE_SHEETS';
