import { CHATGPT_WIDGET_URIS, MCP_APP_WIDGET_MIME_TYPE } from "@/mcp/apps/widget-resources";
import type { McpResourceContract } from "./types";

export const MCP_RESOURCE_CONTRACTS: McpResourceContract[] = [
  { name: "workflow-schema", uri: "a8n://schema/workflow", profiles: ["default", "chatgpt"], kind: "resource", mimeType: "text/markdown", requiredScopes: [], modelVisible: true, widgetOnly: false, note: "Workflow graph shape reference." },
  { name: "node-types", uri: "a8n://schema/node-types", profiles: ["default", "chatgpt"], kind: "resource", mimeType: "text/markdown", requiredScopes: [], modelVisible: true, widgetOnly: false, note: "Node type reference generated from manifest." },
  { name: "credential-types", uri: "a8n://schema/credential-types", profiles: ["default", "chatgpt"], kind: "resource", mimeType: "text/markdown", requiredScopes: [], modelVisible: true, widgetOnly: false, note: "Credential metadata/security reference." },
  { name: "api-docs", uri: "a8n://docs/api", profiles: ["default", "chatgpt"], kind: "resource", mimeType: "text/markdown", requiredScopes: [], modelVisible: true, widgetOnly: false, note: "MCP tool API docs." },
  { name: "node-catalog", uri: "a8n://catalog/nodes", profiles: ["default", "chatgpt"], kind: "resource", mimeType: "application/json", requiredScopes: [], modelVisible: true, widgetOnly: false, note: "Machine-readable node catalog." },
  { name: "credential-catalog", uri: "a8n://catalog/credentials", profiles: ["default", "chatgpt"], kind: "resource", mimeType: "application/json", requiredScopes: [], modelVisible: true, widgetOnly: false, note: "Machine-readable credential catalog without secret values." },
  { name: "integration-setup-template", uri: "a8n://integrations/{service}/setup", profiles: ["default", "chatgpt"], kind: "template", mimeType: "text/markdown", requiredScopes: [], modelVisible: true, widgetOnly: false, note: "Integration setup guide template." },
  { name: "mcp-app-catalog", uri: "a8n://apps/catalog", profiles: ["default", "chatgpt"], kind: "resource", mimeType: "application/json", requiredScopes: [], modelVisible: true, widgetOnly: false, note: "Catalog of app-style resources." },
  { name: "workflow-draft-preview-app", uri: "a8n://apps/workflow-drafts/{draftId}/preview", profiles: ["default", "chatgpt"], kind: "template", mimeType: "text/html", requiredScopes: ["workflows:read"], modelVisible: true, widgetOnly: false, note: "Authenticated workflow draft preview resource." },
  { name: "workflow-setup-checklist-app", uri: "a8n://apps/workflows/{workflowId}/setup-checklist", profiles: ["default", "chatgpt"], kind: "template", mimeType: "text/html", requiredScopes: ["workflows:read"], modelVisible: true, widgetOnly: false, note: "Authenticated setup checklist resource." },
  { name: "execution-timeline-app", uri: "a8n://apps/executions/{executionId}/timeline", profiles: ["default", "chatgpt"], kind: "template", mimeType: "text/html", requiredScopes: ["executions:read"], modelVisible: true, widgetOnly: false, note: "Authenticated execution timeline resource." },
  { name: "workflow-draft-approval-app", uri: "a8n://apps/workflow-drafts/{draftId}/approval", profiles: ["default", "chatgpt"], kind: "template", mimeType: "text/html", requiredScopes: ["workflows:read"], modelVisible: true, widgetOnly: false, note: "Authenticated approval resource with confirmation hash." },
  { name: "chatgpt-workflow-draft-preview-widget", uri: CHATGPT_WIDGET_URIS.workflowDraftPreview, profiles: ["chatgpt"], kind: "widget", mimeType: MCP_APP_WIDGET_MIME_TYPE, requiredScopes: [], modelVisible: false, widgetOnly: true, note: "ChatGPT widget resource." },
  { name: "chatgpt-workflow-setup-checklist-widget", uri: CHATGPT_WIDGET_URIS.workflowSetupChecklist, profiles: ["chatgpt"], kind: "widget", mimeType: MCP_APP_WIDGET_MIME_TYPE, requiredScopes: [], modelVisible: false, widgetOnly: true, note: "ChatGPT widget resource." },
  { name: "chatgpt-execution-timeline-widget", uri: CHATGPT_WIDGET_URIS.executionTimeline, profiles: ["chatgpt"], kind: "widget", mimeType: MCP_APP_WIDGET_MIME_TYPE, requiredScopes: [], modelVisible: false, widgetOnly: true, note: "ChatGPT widget resource." },
  { name: "chatgpt-workflow-approval-widget", uri: CHATGPT_WIDGET_URIS.workflowApproval, profiles: ["chatgpt"], kind: "widget", mimeType: MCP_APP_WIDGET_MIME_TYPE, requiredScopes: [], modelVisible: false, widgetOnly: true, note: "ChatGPT widget resource." },
];
